### ISSUE TITLE
Replace "Tournament" section with formatted rich text page

### ISSUE THREAD

**Issue by cdobbyn** [BCGamer/website#111]
Removed "Tournament" section from index.html as it does not belong there, this page is not editable by content staff.

Generate and format a rich text page to display not only the primary tournaments but also basic events that will take place at lantasy 2016.

Let me know if you need help with this. I recommend doing both of these steps:
1. Do a manage.py datadump to see what the end model looks like
2. Dig into the mezzanine models and see what's not required (blank=True, null=True)

**Comment by Neoburn** [comment]
Completed. Ready for updates

**Comment by cdobbyn** [comment]
@Neoburn - If you mark the issue id and say "closes" or "closed by" when you push the content up to develop the issue will automagically close.

**Comment by Neoburn** [comment]
Magic is heresy.
