### ISSUE TITLE
Adjust footer

### ISSUE THREAD

**Issue by cdobbyn** [BCGamer/website#168]
Adjust custom.css - footer ul {} remove top -10px
Adjust font-size 12px
-shawlogo should not be "copyrights-left"
-shawlogo should be center-aligned always
Remove pull-right from social icons div

When @media > 769px:
-copyrights-left should be right-aligned
-copyrights-right should be left-aligned
-footer .fa should have a padding-top:17px

When @media < 769px:
-copyrights-left should be center-aligned
-copyrights-right should be center-aligned

**Comment by cdobbyn** [comment]
I need to review, if this is working properly locally we've got an issue with auto-upload to staging (css not updating). This did not apply to staging.

**Comment by cdobbyn** [comment]
Remove padding-top:17px because I'm crazy. Thanks.

**Comment by Neoburn** [comment]
Removed the padding.
