### ISSUE TITLE
Display of Drop In Events

### ISSUE THREAD

**Issue by angelamgruber** [BCGamer/website#239]
When an event is set to 0 participants - can we show "Drop in" for Size and Available instead of what is currently being displayed - it is very misleading and could cause confusion if the players do not read the description.  This will be needed for RPG Games on Demand and LAN 7 Days to Die (and any other no registration events that may exist)

![lan_01](https://cloud.githubusercontent.com/assets/13388551/12357492/0502f3be-bb5d-11e5-8d37-30ac99cc558f.PNG)

**Comment by cdobbyn** [comment]
"Disable registration" exists within staging currently. This currently just hides the "size" and "available" fields. Can change to display "Drop in" or "Drop in event".
