### ISSUE TITLE
Change requested to Lantasy 2016 listing of all events

### ISSUE THREAD

**Issue by angelamgruber** [BCGamer/website#240]
On the Lantasy 2016 (start of the breadcrumb - http://staging.lantasy.com/convention/lantasy-2016/) currently every event is listed.  I believe this is in progress but I do not think it is needed.  Could the events be replaced with the headings (LAN Games, Board Games, Tabletop Minis, etc) and if clicked on the user would be taken to that page in the breadcrumb. (I.e. clicking on RPG Games would take the user here http://staging.lantasy.com/event_type/rpg-games/ )

![capture](https://cloud.githubusercontent.com/assets/13388551/12357546/41fd7302-bb5d-11e5-9b51-890f5569053d.PNG)

**Comment by cdobbyn** [comment]
Changing to only display the categories. This should clean up this page a bit for when we add more content.
