### ISSUE TITLE
Ticket Types displayed not correct for RPG Games - Games on Demand

### ISSUE THREAD

**Issue by angelamgruber** [BCGamer/website#241]
Games on Demand has sessions on two different days, the ticket types section does not include the Saturday passes that are applicable for the two Saturday sessions.  It is only displaying the ticket type information for the Sunday sessions.

![capture](https://cloud.githubusercontent.com/assets/13388551/12357737/7aa6638e-bb5e-11e5-8946-cc2612db44c5.PNG)

**Comment by cdobbyn** [comment]
I will make ticket type render on each event instance.

**Comment by cdobbyn** [comment]
Fixed by 60dd745.
