### ISSUE TITLE
On Ticket Details render out ticket option details / total price

### ISSUE THREAD

**Issue by cdobbyn** [BCGamer/website#250]
![ticket_detail](https://cloud.githubusercontent.com/assets/8264498/12565199/40656262-c368-11e5-959d-9e3736da4874.JPG)

This would require adding the specific details of what a ticket option allows you to do  into the ticket option details. These ARE ticket specific so nothing special will be required to accomplish this.

Just a loop spitting out the title/description/calculated price.

**Comment by cdobbyn** [comment]
http://staging.lantasy.com/tickets/weekend-pass/

**Comment by graphit3** [comment]
Confusing how it displays price for weekend pass.

Suggested fixes:
-remove the price at the top
Or
-display add ons as +X Dollars (not the total price)

**Comment by cdobbyn** [comment]
This has been complete for a while.
