### ISSUE TITLE
Need to have MULTIPLE sponsors for an event

### ISSUE THREAD

**Issue by graphit3** [BCGamer/website#256]
With the advent of gaining a recent sponsor, and possible closure of another event, we will have many substantial prizes from many sponsors for a single event. No one sponsor would be solely representing this event in prizes. We desperately need this capability to keep sponsors happy.

Something like below where we can have a button to add another sponsor
![sponsor](https://cloud.githubusercontent.com/assets/15225074/12792077/fb2ed964-ca5e-11e5-8486-159d2840b86b.png)

**Comment by cdobbyn** [comment]
-Change from foreign key to many to many and migrate the existing data:
http://stackoverflow.com/questions/2224410/django-data-migration-when-changing-a-field-to-manytomany
-Modify template to loop through the results (can no longer expect only one or None result)
-Change the m2m field use horizontal filter in admin.
-Modify import to support multiple sponsors.

**Comment by cdobbyn** [comment]
Fixed in b1396cb
