### ISSUE TITLE
Google map is marking the wrong location

### ISSUE THREAD

**Issue by cdobbyn** [BCGamer/website#5]
Currently downtown Victoria. I'm assuming this just needs to be fed some correct coordinates somewhere. Should be pretty easy.

**Comment by wallacetech** [comment]
Corrected address to Pearkes Arena

**Comment by cdobbyn** [comment]
This only occurs when expanding or shrinking the page. This is a minor cosmetic bug and not a major issue.

Likely can be fixed by a js redraw similar to what we're doing with the flexslider pane.

**Comment by Neoburn** [comment]
Fixed in pull #37
