### ISSUE TITLE
Add Pass info to confirmation email and receipt PDF

### ISSUE THREAD

**Issue by mrbaboon** [BCGamer/website#92]

**Comment by cdobbyn** [comment]
Added templates used for this in 3ab753e. Just 2 django formatted HTML templates.

**Comment by cdobbyn** [comment]
Looks like it would be fairly easy to add our branding into the receipt that's generated so that's rad.

**Comment by mrbaboon** [comment]
MAKE THIS NOT SUCK DOBBO.

DONT LET YOUR DREAMS BE DREAMS.

Use one of these email templates.
https://www.sendwithus.com/resources/templates

**Comment by mrbaboon** [comment]
http://www.mailgun.com/

**Comment by cdobbyn** [comment]
@mrbaboon - The templates on that page are ok, but not html standards compliant; Lots of <center> and <b> tags which are deprecated and the table format is messed up. That being said it's a good start. 

Temporary test redirect url setup for this: http://staging.lantasy.com/test. Some changes I've done have not been pushed upstream so if Jeff looks at this comment don't consider this final at all. Just trying to figure out what I want each "ticket_option" object to look like in terms of the table.

**Comment by cdobbyn** [comment]
@Neoburn - I will get the basic table setup tonight and then hand over to you to implement formatting for email. Will keep you informed.

**Comment by cdobbyn** [comment]
Partially fixed in 773a435

**Comment by cdobbyn** [comment]
Mail template replaced with issue #137. Original issue closed in 020cd15. Closing
