### ISSUE TITLE
Verify discount codes work as required.

### ISSUE THREAD

**Issue by mrbaboon** [BCGamer/website#96]

**Comment by cdobbyn** [comment]
This element appeared to be hidden on the checkout form template. It doesn't even display as an option if there are none. This should just work out of box.

**Comment by cdobbyn** [comment]
This element remains hidden after a discount code has been made available. Will need further investigation.

**Comment by cdobbyn** [comment]
This is important because it will be used by certain trusted vendor's to sell tickets on behalf of LANtasy.

**Comment by mrbaboon** [comment]
Dobbo is bad.
